16-SulGore/Algorithm

1436.py
- [1436 ] 영화감독 숌
6의 개수를 세는 for문 안에 len(num) - j 같은 문장을 많이써서 가독성이 떨어지는 것 같아요 어떻게 적는게 더 깔끔하고 좋을까요??
=> 1436: 영화감독 숌

class2/1654.py, class2/1874.py, class2/1920.py, class2/1929.py
=> 1주차 - class 2

Class4/bag.py, Class4/binary_search.py, Class4/fibonacci6.py
#13 
1. 시간초과 문제들
- 피보나치와 배낭 문제에서 시간초과가 떴습니다. 아직 해결방안을 생각하면서 문제를 푸는 중입니다.
2. 재귀 횟수 늘리기
- 이분 검색 트리 문제를 풀면서 인덱싱을 해 해당 배열을 인자로 넘겨주는 방식을 택했습니다. 이 방법은 재귀로 진행되며 재귀 리밋을 넘어가 좀더 늘려주는 방식을 택했습니다. 늘리지 않고 하는 방법은 없는지 궁금합니다.
=> Class4 시간초과 문제들

data_structure/tree/main.py, data_structure/tree/model/BPlusTree.py, data_structure/tree/model/Node.py, data_structure/tree/test/BPlusTreeTest.py
- 구현하면서 딱히 머리에 들어오지 않아서 현타가 온 상태
=> b+tree 구현 (미완)

programmers/level1/easy/ex_01.py, programmers/level1/easy/ex_02.py, programmers/level1/easy/ex_03.py, programmers/level1/easy/ex_04.py, programmers/level1/kakao/ex_03.py, programmers/level1/kakao/ex_04.py, programmers/level1/kakao/ex_05.py, programmers/level1/kakao/ex_06.py, programmers/level1/kakao/test.py
resolve: #22
- 1단계 4문제 해결
- 카카오 4문제 해결
=> 프로그래머스 1주차 모각코

week_01/괄호변환.py
- #26 
- 괄호 변환
그냥 하라는 대로 구현했습니다!!
=> [BDH]괄호 변환

week_01/오픈채팅방.py
- #26 
- 오픈채팅방
- 닉네임 변경가능함
- 포인터 느낌으로 풀고 싶었음
- `uid`만 기억하고, `uid`가 마지막에 가리키는 닉네임만 확인하자!
=> [BDH]오픈 채팅방

kakao/0411_오픈채팅방.py
- #26
- 오픈채팅방
- enum 클래스 사용
- 객체지향
- solution 함수 내의 parse 함수에서 2개로 스플릿할 때, 3개로 스플릿할 때를 구분하는 기능을 함수로 세분화하고 싶은데 마땅히 이름을 짓기가 힘드네요.
=> [CJW]오픈채팅방

programmers/jacquard.py, programmers/open_chat.py
- #26 
- 오픈 채팅방
다른 분들 코드를 보니깐 훌륭하시네요....
저는 그냥 원본데이터를 반복문 두번돌려 dict을 사용해 풀었습니다
=> [KJH] 오픈채팅방

kakao/0413_메뉴리뉴얼.py
- #26 
- 접근 자체가 틀린 풀이입니다.
- 이거 레벨2 개구라임ㄹㅇ
- 메뉴 리뉴얼
- 코드가 예쁜지만 봐주세요,, 허허 로직이 다 틀렸습니다.
=> fail: 메뉴 리뉴얼

kakao/0414_괄호변환.py
- #26
- 괄호변환
- 마지막에 작성한 reverse_bracket 함수를 줄일 수 있을까?
=> [CJW] 괄호변환

kakao/0416_거리두기확인하기.py, kakao/0416_뉴스클러스터링.py, kakao/0416_수식최대화.py
- #27
- enum이 번거롭다고 느끼고 전역 상수를 활용하는 방식으로 변경
=> [CJW] 3문제 해결

week_01/뉴스클러스터링.py
- #27 
- 뉴스 클러스터링
개수를 세야해서 `Counter` 불러와서 사용했습니다.
처음에는 `str_to_elements` 함수 없이 바로 때려 박았는데 중복 코드가 보기 싫어서 만들었습니다.
```python
A = Counter([str1[i:i+2].upper() for i in range(len(str1) - 1) if str1[i:i+2].isalpha()])
B = Counter([str1[i:i+2].upper() for i in range(len(str1) - 1) if str1[i:i+2].isalpha()])
```
=> [BDH]뉴스 클러스터링

week_01/거리두기확인하기.py
- #27 
- 거리두기 확인하기
`check_distance` 함수안에서 `bfs`를 하는데 함수가 너무 길어서 세분화 하려고 하는데 세분화 하는게 어렵습니다.
10~25줄을 `bfs()`를 새로 만드려고 헀는데 그럼 `i`, `j`말고도 `place`를 매개변수로 전달해야하는데 그렇게 되면 너무 큰 덩어리가 왔다갔다 하는 느낌이라 좋은 코드같은 느낌이 안드네요.
```python
from collections import deque
ROW = COL = 5
def bfs(i, j, place):
direction = [(-1, 0), (1, 0), (0, -1), (0, 1)]
visited = [[0 for _ in range(ROW)] for _ in range(COL)]
q = deque([(i, j, 0)])
while q:
now_i, now_j, distance = q.popleft()
visited[now_i][now_j] = 1
for di, dj in direction:
next_i = now_i + di
next_j = now_j + dj
if 0 <= next_i < ROW and 0 <= next_j < COL:
if not visited[next_i][next_j] and distance < 2:
if place[next_i][next_j] == 'O':
q.append((next_i, next_j, distance + 1))
elif place[next_i][next_j] == 'P':
return False
return True
def check_distance(place): …
```
=> [BDH]거리두기 확인하기

week_01/수식최대화.py
- #27 
`class`를 한번 써보고 싶었달까..!!
연산자가 피연산자들을 가리키고 있다고 생각하고 연결리스트처럼 풀어봤습니다.
=> [BDH] 수식최대화

week_1/오픈채팅방.py
- #26
- 오픈채팅방
- dict 사용을 지양하고 싶지만 못한 것 같네요
- 더 깔끔하게 작성하고 싶다랄까..
=> [PSH] 오픈채팅방

week_1/메뉴리뉴얼.py
- #26 
* 일련의 과정들이 함수화되지 않고 하나의 반복문에서 모든 것을 해결하여 가독성이 저하될까 우려
=> [PSH] 메뉴 리뉴얼

week_1/괄호변환.py
- #26
- 문자열 조작, Array가 좋은가 String이 좋은가?
=> [PSH] 괄호 변환

week_1/거리두기 확인하기.py, week_1/뉴스 클러스터링.py, week_1/수식 최대화.py
- #27
- 문제를 한번에 늦게 올려서 죄송합니다~~~ (여행 이슈)
=> [PSH] #27 3문제 해결

kakao/0417_튜플.py, kakao/0417_튜플_refactor.py, kakao/0417_튜플_short.py
- #27
```python
class CustomList:
def __add__(self, other):
덧셈_오버로딩
def __sub__(self, other):
뺄셈_오버로딩
a = CustomList()
b = CustomList()
a + b
a - b 
```
- reduce 사용
- 차집합이 안된다 생각했는데 다시 해보니 잘됨
- 차집합도 하고 reduce도 한김에 숏코딩도 해버림
=> [CJW] 튜플튜플튜플튜플

kakao_kt/src/main/kotlin/0421_후보키.kt, kakao_kt/src/test/kotlin/CandidateKeyTest.kt
- #41
- 코틀린은 combination이 제공되지 않는다. 백트래킹으로 구현했음
- 입출력 예제를 넣기도 힘들다.
- 이전 프로젝트에서 알고리즘적인 고민을 한게 있었는데, 코테준비를 코틀린으로 했다면 코드가 달라졌을 것 같다. 리팩터링 의사가 생김
=> [CJW] 후보키 (kt)

week_02/캐시.py, week_02/프렌즈4블록.py
=> [BDH] 2문제 해결

week_02/방금그곡.py, week_02/압축.py, week_02/캐시.py, week_02/프렌즈4블록.py
- #41 
이상하게 커밋이 따라오네용.. **방금그곡**, **압축**만 봐주세요!! 죄송합니다!!
=> [BDH] 2문제해결(방금그곡, 압축)

week_2/프렌즈4블록.py
=> [PSH] 프렌즈 4블록

week_3/자물쇠와 열쇠.js, week_3/자물쇠와 열쇠.py
- #59 
* Python과 Javascript 간의 차이가 구현 방식을 너무 다르게 만드는 것 같다
* Python 에서 짜잘한 변수 처리를 어떻게 하면 좋을까?
* JavaScript의 for문과 고차함수, 무엇을 사용해야 할까? 기준이 모호하다
* 알고리즘 고민사항
- 자물쇠를 기준으로 고민했다 (겹치는 부분 XOR 만 고려)
- 자물쇠에서 홈 전부를 열쇠가 채워줘야 했다 (count 변수 생성 이유)
=> [PSH] 자물쇠와 열쇠

week_3/표 편집.js, week_3/표 편집.py
- #59 
* 자료구조의 혼란
- 이동의 경우 시간이 엄청 오래 걸린다... (ex/ "U 123456", "D 123456")
- 과연 double linked list를 사용하는 것이 맞는지?
- 이분 탐색과 같은 방법을 사용할 수 있지 않을까?
* Python 에서 linked list 구현을 처음 해보았는데... 가독성이 좀 구린 듯
=> [PSH] 표 편집

week_4/경주로 건설 시간초과.py, week_4/경주로 건설.js, week_4/경주로 건설.py
- #65
* 처음 DP + BFS 에서 예외가 없을 줄 알았는데... ㅜ
* 이전의 길 까지 포함해서 3개를 고려하는 방식으로 작성했을 때 -> 시간 초과가 떴음
- 3차원 배열 밖에 방법이 없었을까
* 케이스
[[0, 0, 0, 0, 0], [0, 1, 1, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 1], [0, 1, 1, 0, 0]]
* 결과
3000
=> [PSH] 경주로 건설

week_4/광고 삽입.js, week_4/광고 삽입.py
=> [PSH] 광고 삽입

kakao_kt/src/main/kotlin/0506_징검다리건너기.kt
- #65
- 이분탐색은 코틀린스러운 코드로 풀기 애매한듯
=> [CJW] 징검다리 건너기

kakao_kt/src/main/kotlin/0506_길찾기게임.kt
=> [CJW] 길찾기 게임

kakao_kt/src/main/kotlin/0505_기둥과보설치.kt
- #65
- forEach를 세 번 깊숙히 들어가는 로직을 콜백함수로 간단히 변경
```kotlin
private fun boardForEach(block: (x: Int, y: Int, builtType: Int, built: Boolean) -> Unit) {
board.forEachIndexed { x, line ->
line.forEachIndexed { y, cell ->
cell.forEachIndexed { builtType, built ->
block(x, y, builtType, built)
}
}
}
}
```
```kotlin
boardForEach { x, y, builtType, built ->
if (built) result = result && canBuild(intArrayOf(x, y, builtType, 1).toBuild())
}
```
- kotlin은 특이하게 if문을 지양하고 switch/case문을 적극적으로 사용합니다. 이유는 가독성~
```kotlin
when (a) {
is Int -> {}
is String -> {}
}
```
=> [CJW] 기둥과 보 설치

kakao_kt/src/main/kotlin/0421_후보키.kt, kakao_kt/src/main/kotlin/0503_경주로건설.kt, kakao_kt/src/test/kotlin/CandidateKeyTest.kt
=> [CJW] 경주로 건설

programmers/build_road.py
#65 
- 경주로 건설
2차원 배열을 사용해 비용을 계산하였는데 마지막 케이스에서 막혀서 해설을 참고했더니 3차원 배열을 사용해 코너의 갯수까지도
고려해야하던데 야매(?)로 엣지케이스를 풀어버렸네요.. 혹시 3차원 배열로 풀어주시는 분 있으신가요
해당 링크에서 엣지케이스에 대한 설명이 있습니다. 
https://programmers.co.kr/questions/21325
=> [KJH] 경주로 건설

programmers/column_row.py
#65 
- 기둥과 보의 설치 조건을 valid 함수 안에서 다 구현했습니다.
- solution 안에서는 설치 삭제 조건을 나누어 작성했습니다. 
- wall 배열은 좌표에 기둥과 보의 유무를 담기 위해 작성된 3차원 배열입니다.
- 삭제 조건 경우의 수를 계속 생각하다가 실패해서 삭제하고 남은 모든 기둥과 보의 valid 상황을 판단해 삭제해나갔습니다.
- 더 효율적인 풀이가 뭐가 있을까 고민이 됩니다...
=> [KJH] 기둥과 보 설치

.gitignore, naver/week01/1654_랜선자르기.py
- #81 
- 이진탐색과 매개변수탐색(파라메트릭서치) 의 차이를 아직 인지하지 못했음
- 2^31 - 1을 표현하기 힘들어서 그냥 랜선의 최댓값으로 해버림
- reduce 맛깔나게 사용
- 이진탐색은 사소한 1차이를 확인하기 힘든 것 같다. 최종결과가 end라는 것을 자명하게 답할 수 없음. 경험이 더 필요하다.
=> [CJW] 랜선자르기

naver/week01/2805_나무자르기.py
- #81
이분탐색 컷~
- 최대, 최소값과 start, mid, end 경계선을 이해했다.
- 나무의 길이는 mid값과 비례하기 때문에 파라메트릭 서치를 사용할 수 있었다.
- 정렬된 조건에서 파라메트릭 서치를 사용할 수 있으며 효율성 관련 문제에서 유용할 수 있다.
=> [CJW] 나무자르기

naver/week01/14003_LIS5.py
- #81
- #94 를 응용했다.
- 위치할 수 있는 순서에 대한 배열을 생성했다.
|10|20|10|30|
|--|--|--|--|
|1|2|1|3|
- 해당 배열을 거꾸로 뒤집어 3, 2, 1 순서대로 배열을 생성했다.
- 그걸 또 뒤집어서 해결
- 플레문제 급은 아닌거 같다.
=> [CJW] 가장 긴 증가하는 부분수열 5

naver/week01/2473_세용액.py
- #81
-  #92 와 유사하게 해결
- 이분탐색으로 해결하려 해봤으나 논리가 안맞는다.
=> [CJW] 세 용액

naver_01/1654_랜선자르기.py
=> [BDH] 랜선 자르기

naver_01/2473_세용액.py
- #81 
`pypy3`에서 통과됩니다. `python3`는 시간초과...
=> [BDH] 세 용액

.gitignore, kakao_kt/gradlew
=> hotfix: intelij로 이전

termProject.js
- 관련된 issue #98 
- 참고링크 : 
문제 해설 : https://claude-u.tistory.com/435
재귀 탈출 : http://10bun.tv/beginner/episode-4/#%E1%84%80%E1%85%A1%E1%86%BC%E1%84%8B%E1%85%B4-%E1%84%80%E1%85%A2%E1%84%8B%E1%85%AD
- JS에선 메모리 초과라 python으로도 문제를 한 번 풀어보겠습니다. 
1. 처음 문제를 풀었을 때 재귀 탈출 조건으로 로직을 짜서 해결하는 문제라고 생각함. 
그래서 막 탈출조건에서 로직을 짜려고 생각하니까 문제를 너무 어렵게 접근한 것 같다.
2. JS로 파이썬과 같은 풀이로 문제를 풀었는데 메모리 초과 발생
-> 어쩌면 파이썬으로 코테를 보는 게 현명할 수도 있겠다라고 생각이 듦
```javascript
dfs(x){
if(탈출조건){
return
}
dfs(x+1);
// 탈출행위
return;
}
```
<p align="center">
</p>
=> [HJS] 텀 프로젝트

README.md, archive/kakao.md, goDown.js, goDown.py
관련된 이슈 : #81 
참고한 링크 : https://www.youtube.com/watch?v=ySECi-s5fQY
PS 커밋을 보면 이전 풀이도 볼 수 있어요!!
- JS로 처음 min, max 2차원 배열을 생성하여 DP 방식으로 문제를 품 -> 메모리 초과
- 메모리를 2차원 배열이 아닌 1차원배열로 구성하여 최대 최솟값을 구하였다. -> JS 메모리초과, python 통과 (같은 풀이)
파이썬과 JS가 같은 풀이임에도 불구하고 파이썬은 통과하고 JS는 통과하지 못하는 불가사의한 일이 벌어짐
심지어는 js로 맞추신 분 코드를 다시 제출하니 메모리 초과가 발생하였다. 
그래서 그냥 이 문제는 js는 통과시켜주지 않는다고 판단하였다.
왜 js는 통과시켜주지 않고 python은 통과시켜줄까용??
=> [HJS] 내려가기

README.md, archive/kakao.md, treeCutting.js
- 참고링크 : https://cjh5414.github.io/binary-search/
- 반복문 뿐만 아니라 재귀로도 구현해 봄
- 재귀 동작과정에 대해서도 고민을 좀 해보았음!!
=> [HJS] 나무자르기

boj/1316.py, boj/16236.py
=> [CJW] 아기상어
